FROM scratch AS base

FROM golang:1.23 AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/build/main cmd/balancer/main.go

FROM base AS final
WORKDIR /app
COPY --from=build /app/build .
CMD ["./main"]