env: development
port: 8080
servers:
  - address: http://server1:8080
    health_path: /health
  - address: http://server2:8080
    health_path: /health
algorithm: least-connections

health_check_interval: 60s
health_check_timeout: 10s

dial_timeout: 30s
keep_alive: 30s
max_idle_conns: 100
max_idle_conns_per_host: 10
idle_conn_timeout: 90s

shutdown_timeout: 10s